### ISSUE TITLE
function name maybe wrong

### ISSUE THREAD

**Issue by sandgate-dev** [learn-co-curriculum/partial-derivatives-lab#2]
In [7] has four predefined function names where the last one is name three_x_y_at_nine. At In [9] the last function call is named three_x_y_at_six(2) with a given solution of 36. I am guessing that you meant to call three_x_y_at_nine(2) in order to get to the solution of 36.

**Comment by mas16** [comment]
Hi osterburg! Thanks for the note. Take a look at what happens when you plug in 2 for x in three_x_y_at_six.
