### ISSUE TITLE
Possible mistake in the solution to the lab

### ISSUE THREAD

**Issue by AnnaLara** [learn-co-curriculum/partial-derivatives-lab#5]
I believe the solution to the following functions has a mistake:

def df_dx(list_of_terms):
    derivative_terms = list(map(lambda function_term: term_df_dx(function_term),list_of_terms))
    return list(filter(lambda derivative_term: derivative_term[0] > 0, derivative_terms))

def df_dy(list_of_terms):
    derivative_terms = list(map(lambda function_term: term_df_dy(function_term),list_of_terms))
    return list(filter(lambda derivative_term: derivative_term[0] > 0, derivative_terms))

Terms where derivative_term[0] < 0 should not be filtered out because the constant can have a negative value. Thus, the therm (-4, 2 , 1) representing -4*x^2*y would be filtered out, which is wrong. Only terms where the constant is equal to 0 should be filtered out. 

I believe the right way to define this functions would be:

def df_dx(list_of_terms):
    derivative_terms = list(map(lambda function_term: term_df_dx(function_term),list_of_terms))
    return list(filter(lambda derivative_term: derivative_term[0] != 0, derivative_terms))

def df_dy(list_of_terms):
    derivative_terms = list(map(lambda function_term: term_df_dy(function_term),list_of_terms))
    return list(filter(lambda derivative_term: derivative_term[0] != 0, derivative_terms))

**Comment by mas16** [comment]
Thanks AnnaLara! This has been corrected.
